# Generated by Django 4.1 on 2022-10-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='jumlah',
            field=models.IntegerField(null=True),
        ),
    ]
