# Generated by Django 4.1 on 2022-10-05 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0002_dosen_jumlah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosen',
            name='jumlah',
        ),
    ]
